[project]
name = "sba-928-hima-tella"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hbTella", email = "hima02@yahoo.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.6",
    "torch>=2.14.1",
    "transformers>=5.18.0",
]

[project.scripts]
sba-928-hima-tella = "sba_928_hima_tella:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
